RUN:
    out: ./out/ctv
    in: ./instCtV
GA:
    generationcount: 200
    generationsize: 100
    mutation: 0.05
    crossover: 0.7
    selection: 0.01 1.5 0.1
    selection_add: 0
    elitism: 1
    fitness: 0.99
