RUN:
    out: ./out/t
    in: ./instCtV
GA:
    generationcount: 410
    generationsize: 410
    mutation: 0.05 0.21 0.05
    crossover: 0.6
    selection: 0.36
    selection_add: 2
    elitism: 1
    fitness: 0.99
