RUN:
    out: ./out/t
    in: ./instNV
GA:
    generationsize: 500
    generationcount: 200
    mutation: 0.03
    crossover: 0.5 1 0.1
    selection: 0.1
    selection_add: 2
    elitism: 1
    fitness: 0.95
